### ISSUE TITLE
Communication failed

### ISSUE THREAD

**Issue by Nbondb** [PLCHome/growatt#31]
SPH5000

Since 3:00 this morning I get 'communication failed' on attempting getPlatData. Shinephone still works, have Growatt changed something preventing this code to work?
Managed to successfully get/setInverterSetting so looks like just a issue with getPlatDat.

Output from test.js
login: { result: 1 }
Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin
    at /data/data/com.termux/files/home/node_modules/growatt/lib/growatt.js:332:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Thanks

**Comment by LosBagros** [comment]
same

**Comment by PLCHome** [comment]
[lib/growatt.js](https://github.com/PLCHome/growatt/blob/master/lib/growatt.js) changed

**Comment by PLCHome** [comment]
fixed in 0.7.4

**Comment by Nbondb** [comment]
Now I get following

node:internal/modules/cjs/loader:1152
  throw err;
  ^

Error: Cannot find module 'md5'
Require stack:
- /data/data/com.termux/files/home/node_modules/growatt/lib/growatt.js
- /data/data/com.termux/files/home/.termux/tasker/test.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
    at Module._load (node:internal/modules/cjs/loader:990:27)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/node_modules/growatt/lib/growatt.js:26:13)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/data/com.termux/files/home/node_modules/growatt/lib/growatt.js',
    '/data/data/com.termux/files/home/.termux/tasker/test.js'
  ]
}

**Comment by PLCHome** [comment]
RTFM you must install the package. MD5 is added. 

npm install after update the version in your package.json

**Comment by Nbondb** [comment]
Sorry. Now RTFM and all is ok.
Thanks for your quick response and solution.
